const ytdl = require("@distube/ytdl-core");
const agent = ytdl.createAgent([
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.11843,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "UJ3aqRODAefyABbv/ABkCOG2Mm6lF9rw9k",
        "id": 1
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.118619,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000twj4pnHefhp-vF3Jpr9nZ_rEF9l7COk8p3TWdCjDHoJBZrZub_Q1D7PuAsUy9cmzj_BqdwACgYKAdsSARMSFQHGX2Mik5l-JjlAGX2IpVmYCB5M9BoVAUF8yKrsFjyYguDlNgYBsA4ZubPv0076",
        "id": 2
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1772919672.369963,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzXb6HXXWBcHkRwXW5jC8f1MQQ9_Tx9PskbnFFpaNNHyxVJb8o3u9qqGbAmvVVVxdE7H9w",
        "id": 3
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1772919232.793855,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjEBEJ3XVxm0K2xRGaOfsUY_C1VrqoZJNF4HF_s2B9veMGpnMDPnkPKBag3GIou7RzyREAA",
        "id": 4
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.11845,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "UJ3aqRODAefyABbv/ABkCOG2Mm6lF9rw9k",
        "id": 5
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.118636,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a000twj4pnHefhp-vF3Jpr9nZ_rEF9l7COk8p3TWdCjDHoJBZrZug2llLKkpe-riZe2EutC-aAACgYKAbMSARMSFQHGX2Mit03_EJwaewxn5M2YrtPkOxoVAUF8yKodJBEz27mUi2xETdxjb8Sa0076",
        "id": 6
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1772919672.370002,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzWA6TfYNRSXdlKcMiiiSnouAt6MHkCVIIKTcuxejTJ32MApN16hNSa4mi5x60m_4L3xnw",
        "id": 7
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1772919232.793984,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjEBEJ3XVxm0K2xRGaOfsUY_C1VrqoZJNF4HF_s2B9veMGpnMDPnkPKBag3GIou7RzyREAA",
        "id": 8
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1772485073.186142,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-YEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Cgs1ellRNGczY2JHWSj0z62-BjIiCgJSTxIcEhgSFhMLFBUWFwwYGRobHB0eHw4PIBAREiEgOw%3D%3D",
        "id": 9
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.118388,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "lLZzW-spOen4Kvs6/AFcGVeY4igEZcbqTt",
        "id": 10
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.118269,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AGT3aunlQKpo6mGSP",
        "id": 11
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1775941379.508467,
        "hostOnly": false,
        "httpOnly": true,
        "name": "LOGIN_INFO",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AFmmF2swRQIhALPRMC_6NC_eqhYB9KhqOUdjMZwhuF2iiPv5N0tqi1kBAiAVT5ChcWNlRN7J-VWOAFgXQGzbRbqc-tGlkkc9v51eqw:QUQ3MjNmd0NGMEw0MEdDT2hrazBxQzY2bzdiRkJWVWlOOFliZTQzZHBXVjh4ZVNJNnBjb1cyYUI2MW4tWHoxcHV5LUFER25wbk5JN1NQM3lBa1BDY3VwcDNoSTRfbUt0eEV1QjVUREpDanljRmtLQWtKWG1vUEt2R25lVnVlRGRoNW4wTDd4eWZ0VUdFVFd0OVBxMkdINGtyaTdCSWVKMEFn",
        "id": 12
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1775943671.254198,
        "hostOnly": false,
        "httpOnly": false,
        "name": "PREF",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "f6=40000000&f7=100&tz=Europe.Bucharest&repeat=NONE&f4=4000000",
        "id": 13
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.118412,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "UJ3aqRODAefyABbv/ABkCOG2Mm6lF9rw9k",
        "id": 14
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.118598,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a000twj4pnHefhp-vF3Jpr9nZ_rEF9l7COk8p3TWdCjDHoJBZrZuhZE5zGqbo9rB1URegF70SgACgYKAT0SARMSFQHGX2MiWM7cCuw6EW9NOcsrBvManRoVAUF8yKqcpmmLDTG3hgP15kgEGFGS0076",
        "id": 15
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1772919672.369846,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzVYZC-2KJpB-2Rh_85FPPAPQ_k94cfkKtdtRXZGQ3JH9RVQVgv2o2hKKoOZXNoa-xNEU6o",
        "id": 16
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1772485072.857395,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SOCS",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "CAAaBgiApfC8Bg",
        "id": 17
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1774117668.118367,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AkotWykF-qJASj3Bk",
        "id": 18
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1741383675,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ST-l3hjtt",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "session_logininfo=AFmmF2swRQIhALPRMC_6NC_eqhYB9KhqOUdjMZwhuF2iiPv5N0tqi1kBAiAVT5ChcWNlRN7J-VWOAFgXQGzbRbqc-tGlkkc9v51eqw%3AQUQ3MjNmd0NGMEw0MEdDT2hrazBxQzY2bzdiRkJWVWlOOFliZTQzZHBXVjh4ZVNJNnBjb1cyYUI2MW4tWHoxcHV5LUFER25wbk5JN1NQM3lBa1BDY3VwcDNoSTRfbUt0eEV1QjVUREpDanljRmtLQWtKWG1vUEt2R25lVnVlRGRoNW4wTDd4eWZ0VUdFVFd0OVBxMkdINGtyaTdCSWVKMEFn",
        "id": 19
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1741383675,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ST-tladcw",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "session_logininfo=AFmmF2swRQIhALPRMC_6NC_eqhYB9KhqOUdjMZwhuF2iiPv5N0tqi1kBAiAVT5ChcWNlRN7J-VWOAFgXQGzbRbqc-tGlkkc9v51eqw%3AQUQ3MjNmd0NGMEw0MEdDT2hrazBxQzY2bzdiRkJWVWlOOFliZTQzZHBXVjh4ZVNJNnBjb1cyYUI2MW4tWHoxcHV5LUFER25wbk5JN1NQM3lBa1BDY3VwcDNoSTRfbUt0eEV1QjVUREpDanljRmtLQWtKWG1vUEt2R25lVnVlRGRoNW4wTDd4eWZ0VUdFVFd0OVBxMkdINGtyaTdCSWVKMEFn",
        "id": 20
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1741383676,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ST-xuwub9",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "session_logininfo=AFmmF2swRQIhALPRMC_6NC_eqhYB9KhqOUdjMZwhuF2iiPv5N0tqi1kBAiAVT5ChcWNlRN7J-VWOAFgXQGzbRbqc-tGlkkc9v51eqw%3AQUQ3MjNmd0NGMEw0MEdDT2hrazBxQzY2bzdiRkJWVWlOOFliZTQzZHBXVjh4ZVNJNnBjb1cyYUI2MW4tWHoxcHV5LUFER25wbk5JN1NQM3lBa1BDY3VwcDNoSTRfbUt0eEV1QjVUREpDanljRmtLQWtKWG1vUEt2R25lVnVlRGRoNW4wTDd4eWZ0VUdFVFd0OVBxMkdINGtyaTdCSWVKMEFn",
        "id": 21
    },
    {
        "domain": ".youtube.com",
        "expirationDate": 1756842845.077094,
        "hostOnly": false,
        "httpOnly": true,
        "name": "VISITOR_PRIVACY_METADATA",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "CgJSTxIcEhgSFhMLFBUWFwwYGRobHB0eHw4PIBAREiEgOw%3D%3D",
        "id": 22
    },
    {
        "domain": ".youtube.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "YSC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "73O1AZ2nvaI",
        "id": 23
    }
]);

module.exports = agent;