const cookie = 
    [
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.98689,
            "hostOnly": false,
            "httpOnly": false,
            "name": "__Secure-1PAPISID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "QJe1XMTNNy9Xy8VY/A-s8h3Reoo9tApUVR",
            "id": 1
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.986967,
            "hostOnly": false,
            "httpOnly": true,
            "name": "__Secure-1PSID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "g.a000qAhsqeIHUH92A-ZNIgDPmvOt8uFnvzlfHo7AHeaAjX4y4ZjbXHue7YSPYqZFu4qHfQDbYAACgYKAfUSARQSFQHGX2MirtiqNmKlQ7LusCJKWl_tFBoVAUF8yKpn4fqNZxud0ELVNFNr1nxb0076",
            "id": 2
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1762721114.72472,
            "hostOnly": false,
            "httpOnly": true,
            "name": "__Secure-1PSIDCC",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "AKEyXzU6MgQAqGziJwwEDC1DFOXjKPptER1__lO_PDDrPRkPwx75Mn1ppZucMV0mxzXo4sN6-g",
            "id": 3
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1762720712.98664,
            "hostOnly": false,
            "httpOnly": true,
            "name": "__Secure-1PSIDTS",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "sidts-CjEBQT4rXwlBnbFLMzTyspPDkjAyA74Psr5jfYinT3lW8zqhQEiYsJ-3qKLQc2DMsbZIEAA",
            "id": 4
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.986912,
            "hostOnly": false,
            "httpOnly": false,
            "name": "__Secure-3PAPISID",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "QJe1XMTNNy9Xy8VY/A-s8h3Reoo9tApUVR",
            "id": 5
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.986993,
            "hostOnly": false,
            "httpOnly": true,
            "name": "__Secure-3PSID",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "g.a000qAhsqeIHUH92A-ZNIgDPmvOt8uFnvzlfHo7AHeaAjX4y4Zjb71LCytpkJPVNCBXa3z6QjgACgYKAbwSARQSFQHGX2Mi6kx9kkxXD-7iFxu3iiF8xBoVAUF8yKpXyHxOXlhp1_-YsmrVo2040076",
            "id": 6
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1762721114.724789,
            "hostOnly": false,
            "httpOnly": true,
            "name": "__Secure-3PSIDCC",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "AKEyXzXcn63FGw88QXucQcdkrA_KGuZWS_wBqzZTYZ4CHLWzWakCU4OhrQ0Bzzav3QQwatmt3Q",
            "id": 7
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1762720712.986761,
            "hostOnly": false,
            "httpOnly": true,
            "name": "__Secure-3PSIDTS",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "sidts-CjEBQT4rXwlBnbFLMzTyspPDkjAyA74Psr5jfYinT3lW8zqhQEiYsJ-3qKLQc2DMsbZIEAA",
            "id": 8
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765312675.356272,
            "hostOnly": false,
            "httpOnly": true,
            "name": "__Secure-YEC",
            "path": "/",
            "sameSite": "lax",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "CgtOU1dhdnBBY3JTbyjVk7-5BjIiCgJSTxIcEhgSFhMLFBUWFwwYGRobHB0eHw4PIBAREiEgKA%3D%3D",
            "id": 9
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.986842,
            "hostOnly": false,
            "httpOnly": false,
            "name": "APISID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "1",
            "value": "GeD92Jgf5ehRaT8h/AekwNY2gEjdaj4UUN",
            "id": 10
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1731185426,
            "hostOnly": false,
            "httpOnly": false,
            "name": "CONSISTENCY",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "AKreu9sWTYq3zlTmyd7kXGM74Ng23JPAy7kl1lwBodNoofD5Pp8rRMVy6PtNJvC4gepwOK6p7xoKIt6Wr-KWpvANGfykK1exrJ-n6EViE5ydhCODR83eEWBRCcaIh0Q-cxnHkyUwGQhLdDFQsKKlzwLd",
            "id": 11
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.986796,
            "hostOnly": false,
            "httpOnly": true,
            "name": "HSID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "1",
            "value": "A1wsk1TvEMr4-FH2T",
            "id": 12
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744713.428717,
            "hostOnly": false,
            "httpOnly": true,
            "name": "LOGIN_INFO",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "AFmmF2swRQIhAMTQ93CW0N_j2L5dRgO_jZ5nlK88KC4dFdWrGJ3pIxWWAiAh7b1i0Fk-AwbOYE-zb1I8Aj5NmKJ2o5iN2qFDy-Upwg:QUQ3MjNmejA4Q1M3S2RpNXBUMVdMcmcyRnN1WGJDcjNfbng4RHZfVk1yT3V0VXczd3dVdWwzd0xmWTNWTVJvakI0TTQxOG9XdVlYaDNISUVDUUZLcF9Ib0FVTHFtT0xHTFRSamh2UWw0X1FBTGprRk1jbks4OWUtdEcyVjZvRTJ0dTQ2VDJFdnVwN0p5ejlrS29nd3lBR19YMjE3NlFfLWt3",
            "id": 13
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1746995918.270002,
            "hostOnly": false,
            "httpOnly": true,
            "name": "NID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "519=ncZvhWfynF4c2nrFl6ZNwBLPGfyck1lu3D__aK5SjoWcs7-3Bv7Cs7V2DeIBi0guFj7MTIkLPl6OmUpRE8U7gsNSsclS5r2W1sAl2vWkkSwWYYzWrzagmBEX9tvLbjDaBbLoVY72E0cgEsoD1oDMcBNw4dxXH_YP8yB1i_AesKoBhapGP2fZxm27vuhxS_xyHCCAOenQDBOq_dDv49KiA4B-26ZDuKoqJhE645CkBm858JJAMFtpMtvgg5FNjggNfH-ZxU9eaBLcg6S41EB4BIERDSTYOG9btio7L0IkbTZgdrYDPj6VZnqGdP327kBL1kstwl9EOkwLIsb0PPoQOcrUx62RREwJRtZC",
            "id": 14
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765745113.542713,
            "hostOnly": false,
            "httpOnly": false,
            "name": "PREF",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "f4=4000000&tz=Europe.Bucharest",
            "id": 15
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.986867,
            "hostOnly": false,
            "httpOnly": false,
            "name": "SAPISID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "QJe1XMTNNy9Xy8VY/A-s8h3Reoo9tApUVR",
            "id": 16
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.986937,
            "hostOnly": false,
            "httpOnly": false,
            "name": "SID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "1",
            "value": "g.a000qAhsqeIHUH92A-ZNIgDPmvOt8uFnvzlfHo7AHeaAjX4y4Zjb72HBphY7ZzehARbTRYU-DwACgYKAUQSARQSFQHGX2MiZKOKhgcpP7xgeGjunbREBBoVAUF8yKpwDlw0jfigOggSetDgIVHc0076",
            "id": 17
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1762721114.72418,
            "hostOnly": false,
            "httpOnly": false,
            "name": "SIDCC",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "1",
            "value": "AKEyXzWjmmAGYZHVgKXPRRxYNtHKg6aVhZMS1STozq5zTWMOjSMhRM5_j8vjR9So-qEbmDvi",
            "id": 18
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1765744712.986821,
            "hostOnly": false,
            "httpOnly": true,
            "name": "SSID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "1",
            "value": "A4Flge5IL1DYZ1HIK",
            "id": 19
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1731185117,
            "hostOnly": false,
            "httpOnly": false,
            "name": "ST-tladcw",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "1",
            "value": "session_logininfo=AFmmF2swRQIhAMTQ93CW0N_j2L5dRgO_jZ5nlK88KC4dFdWrGJ3pIxWWAiAh7b1i0Fk-AwbOYE-zb1I8Aj5NmKJ2o5iN2qFDy-Upwg%3AQUQ3MjNmejA4Q1M3S2RpNXBUMVdMcmcyRnN1WGJDcjNfbng4RHZfVk1yT3V0VXczd3dVdWwzd0xmWTNWTVJvakI0TTQxOG9XdVlYaDNISUVDUUZLcF9Ib0FVTHFtT0xHTFRSamh2UWw0X1FBTGprRk1jbks4OWUtdEcyVjZvRTJ0dTQ2VDJFdnVwN0p5ejlrS29nd3lBR19YMjE3NlFfLWt3",
            "id": 20
        },
        {
            "domain": ".youtube.com",
            "expirationDate": 1731185119,
            "hostOnly": false,
            "httpOnly": false,
            "name": "ST-xuwub9",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "1",
            "value": "session_logininfo=AFmmF2swRQIhAMTQ93CW0N_j2L5dRgO_jZ5nlK88KC4dFdWrGJ3pIxWWAiAh7b1i0Fk-AwbOYE-zb1I8Aj5NmKJ2o5iN2qFDy-Upwg%3AQUQ3MjNmejA4Q1M3S2RpNXBUMVdMcmcyRnN1WGJDcjNfbng4RHZfVk1yT3V0VXczd3dVdWwzd0xmWTNWTVJvakI0TTQxOG9XdVlYaDNISUVDUUZLcF9Ib0FVTHFtT0xHTFRSamh2UWw0X1FBTGprRk1jbks4OWUtdEcyVjZvRTJ0dTQ2VDJFdnVwN0p5ejlrS29nd3lBR19YMjE3NlFfLWt3",
            "id": 21
        }
        ];

module.exports = cookie;